name: mlp_geodesic
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.3.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.13=py312h178313f_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - ase=3.25.0=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - attrs=25.3.0=pyh71513ae_0
  - bibtexparser=1.4.3=pyhd8ed1ab_0
  - blinker=1.9.0=pyhff2d567_0
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - brotli-python=1.1.0=py312h2ec8cdc_3
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - certifi=2025.4.26=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py312h68727a3_0
  - cpython=3.12.11=py312hd8ed1ab_0
  - cuda-crt-tools=12.9.86=ha770c72_1
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-cuobjdump=12.9.82=hbd13f7d_0
  - cuda-cupti=12.9.79=h9ab20c4_0
  - cuda-nvcc-tools=12.9.86=he02047a_1
  - cuda-nvdisasm=12.9.88=hbd13f7d_0
  - cuda-nvrtc=12.9.86=h5888daf_0
  - cuda-nvtx=12.9.79=h5888daf_0
  - cuda-nvvm-tools=12.9.86=he02047a_1
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.10.1.4=h7646684_0
  - cusparselt=0.7.0.0=hcd2ec93_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - docker-pycreds=0.4.0=py_0
  - e3nn=0.5.6=pyhd8ed1ab_0
  - eval_type_backport=0.2.2=pyha770c72_0
  - filelock=3.18.0=pyhd8ed1ab_0
  - flask=3.1.1=pyhd8ed1ab_0
  - fonttools=4.58.4=py312h178313f_0
  - freetype=2.13.3=ha770c72_1
  - frozenlist=1.6.0=py312hb9e946c_0
  - fsspec=2025.5.1=pyhd8ed1ab_0
  - future=1.0.0=pyhd8ed1ab_2
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.44=pyhff2d567_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py312h7201bc8_0
  - grpcio=1.68.2=py312hacea422_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hydra-core=1.3.2=pyhd8ed1ab_1
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - kiwisolver=1.4.8=py312h84d6215_0
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h1423503_5
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcublas=12.9.1.4=h9ab20c4_0
  - libcudnn=9.10.1.4=h4840ae0_0
  - libcudnn-dev=9.10.1.4=hcd2ec93_0
  - libcudss0=0.4.0.2=he55f5cd_2
  - libcufft=11.4.1.4=h5888daf_0
  - libcufile=1.14.1.1=ha8da6e3_0
  - libcurand=10.3.10.19=h9ab20c4_0
  - libcusolver=11.7.5.82=h9ab20c4_0
  - libcusparse=12.5.10.65=h5888daf_0
  - libdeflate=1.24=h86f0d12_0
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libgomp=15.1.0=h767d61c_2
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.68.2=h25350d4_0
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - libllvm20=20.1.7=he9d0ab4_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libmagma=2.8.0=h566cb83_2
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.9.86=h5888daf_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.47=h943b412_0
  - libprotobuf=5.28.3=h6128344_1
  - libre2-11=2024.07.02=hbbce691_2
  - libsqlite=3.50.1=hee588c1_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libsystemd0=257.6=h4e0b6ca_0
  - libtiff=4.7.0=hf01ce69_5
  - libtorch=2.6.0=cuda126_generic_h4a15719_200
  - libudev1=257.6=hbe16f8c_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb9d3cd8_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=h4bc477f_0
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.44.0=py312h374181b_1
  - lmdb=0.9.31=hd590300_1
  - lxml=5.4.0=py312h68d7fa5_0
  - lz4-c=1.10.0=h5888daf_1
  - markdown=3.8=pyhd8ed1ab_0
  - markupsafe=3.0.2=py312h178313f_1
  - matplotlib-base=3.10.3=py312hd3ec401_0
  - monty=2025.3.3=pyhd8ed1ab_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.4.4=py312h178313f_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=1.42.1=pyhe01879c_0
  - nccl=2.27.3.1=h9b8ff78_0
  - ncurses=6.5=h2d0b736_3
  - networkx=3.5=pyhe01879c_0
  - nomkl=1.0=h5ca1d4c_0
  - numba=0.61.2=py312h7bcfee6_1
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.5.0=h7b32b05_1
  - opt-einsum=3.4.0=hd8ed1ab_1
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - opt_einsum_fx=0.1.4=pyhd8ed1ab_1
  - optree=0.16.0=py312h68727a3_0
  - orjson=3.10.18=py312h680f630_1
  - packaging=25.0=pyh29332c3_1
  - palettable=3.3.3=pyhd8ed1ab_1
  - pandas=2.3.0=py312hf9745cd_0
  - pillow=11.2.1=py312h80c1187_0
  - pip=25.1.1=pyh8b19718_0
  - platformdirs=4.3.8=pyhe01879c_0
  - plotly=6.1.2=pyhd8ed1ab_0
  - propcache=0.3.1=py312h178313f_0
  - protobuf=5.28.3=py312h2ec8cdc_0
  - psutil=7.0.0=py312h66e93f0_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-global=2.13.6=pyh217bc35_3
  - pybtex=0.24.0=pyhd8ed1ab_3
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.7=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py312h680f630_0
  - pymatgen=2025.5.28=py312hc0a28a1_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.11=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-lmdb=1.6.2=py312h8fd8f52_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-wget=3.2=py_0
  - python_abi=3.12=7_cp312
  - pytorch=2.6.0=cuda126_generic_py312_h460ed29_200
  - pytorch_geometric=2.6.1=pyhecae5ae_2
  - pytorch_scatter=2.1.2=cuda126py312hf276b08_12
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h178313f_2
  - qhull=2020.2=h434a139_5
  - rdma-core=57.0=h5888daf_0
  - re2=2024.07.02=h9925aae_2
  - readline=8.2=h8c095d6_2
  - requests=2.32.4=pyhd8ed1ab_0
  - ruamel.yaml=0.18.14=py312h66e93f0_0
  - ruamel.yaml.clib=0.2.8=py312h66e93f0_1
  - scipy=1.15.2=py312ha707e6e_0
  - sentry-sdk=2.30.0=pyhd8ed1ab_0
  - setproctitle=1.3.6=py312h66e93f0_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.8=h1b44611_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - spglib=2.6.0=py312hf57cbc4_0
  - submitit=1.5.2=pyhd8ed1ab_0
  - sympy=1.14.0=pyh2585a3b_105
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tensorboard=2.19.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py312hda17c39_2
  - tk=8.6.13=noxft_hd72426e_102
  - tqdm=4.67.1=pyhd8ed1ab_1
  - triton=3.2.0=cuda126py312h5a3d8a8_1
  - typing=3.10.0.0=pyhd8ed1ab_2
  - typing-extensions=4.14.0=h32cad80_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.14.0=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - uncertainties=3.2.3=pyhd8ed1ab_0
  - unicodedata2=16.0.0=py312h66e93f0_0
  - urllib3=2.4.0=pyhd8ed1ab_0
  - wandb=0.20.1=py312h7545c40_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.20.1=py312h178313f_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.23.0=py312h66e93f0_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - ase-db-backends==0.10.0
      - configargparse==1.7.1
      - cryptography==45.0.4
      - fairchem-core==2.2.0
      - h5py==3.14.0
      - hf-xet==1.1.3
      - huggingface-hub==0.33.0
      - lightning-utilities==0.14.3
      - matscipy==1.1.1
      - mypy-extensions==1.1.0
      - numpy==2.2.6
      - prettytable==3.16.0
      - psycopg2-binary==2.9.10
      - pymysql==1.1.1
      - pyre-extensions==0.0.32
      - python-hostlist==2.2.1
      - torch-ema==0.3
      - torchmetrics==1.7.3
      - torchtnt==0.2.4
      - typing-inspect==0.9.0
      - wcwidth==0.2.13
